import { ProductType } from 'models/product-type';

export const productDefaultValue: ProductType = {
  attributes: [],
  category: '',
  createdAt: '',
  currency: '',
  id: '',
  image: '',
  inventoryType: 'in_stock',
  isAvailable: false,
  isShippable: false,
  name: '',
  quantity: 0,
  updatedAt: '',
  variants: 0,
  description: '',
  images: [],
  includesTaxes: false,
  isTaxable: false,
  productCode: '',
  productSku: '',
  salePrice: '',
  price: 0,
};
